#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:30:00
#SBATCH --error=job.err
#SBATCH --output=job.out
#SBATCH --account=INF23_npqcd
#SBATCH --partition=skl_usr_dbg

module load intel

srun ./yang_mills_local_pt_gf input_file_ym_pt_gf
