#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --time=24:00:00
#SBATCH --error=job.err
#SBATCH --output=job.out
#SBATCH --account=INF22_npqcd
#SBATCH --partition=skl_usr_prod

module load intel

srun ./yang_mills_local_pt_gf input_file_ym_pt_gf_10
