#!/bin/bash

NCOLORS=3
STDIM=4
NLEVELS=1

NTHREADS=32

compile_targets='yang_mills_local_pt_agf'

# 1=yes, 0=no
ENABLE_THETA=0
ENABLE_OPENMP=1

flag_theta=''
flag_openmp=''
if [ "${ENABLE_THETA}" -eq '1' ]; then flag_theta='--enable-use-theta'; fi
if [ "${ENABLE_OPENMP}" -eq '1' ]; then flag_openmp='--enable-use-openmp'; fi

chmod +x configure
if [ -d lib/.deps ]; then make clean; fi

# optimized configuration for Marconi (optimized compilation with Intel compiler on Intel Skylake processors)
#module load intel
#./configure N_c=${NCOLORS} ST_dim=${STDIM} Num_levels=${NLEVELS} Num_threads=${NTHREADS} CC=icc CFLAGS='-O3 -axCORE-AVX512 -mtune=skylake -ip -ipo' LIBS="-ldl -lz -lc" ${flag_openmp} ${flag_theta}

# optimized configuration for Leonardo (optimized compilation with Intel compiler on Intel Icelake processors)
module load intel-oneapi-compilers
./configure N_c=${NCOLORS} ST_dim=${STDIM} Num_levels=${NLEVELS} Num_threads=${NTHREADS} CC=icc CFLAGS='-O3 -axCORE-AVX512 -mtune=icelake -ip -ipo' LIBS="-ldl -lz -lc" ${flag_openmp} ${flag_theta}

# optimized compilation with gcc
#./configure CC=gcc CFLAGS='-O3' LIBS="-ldl -lz -lc"

# compile
make ${compile_targets} -j 32
