#!/bin/bash

NCOLORS=3
STDIM=4
NLEVELS=1

NTHREADS=48

compile_targets='yang_mills_local_pt_agf yang_mills_gradflow_all_conf debug_agf_vs_gf'

# 1=yes, 0=no
ENABLE_THETA=0
ENABLE_OPENMP=1

flag_theta=''
flag_openmp=''
if [ "${ENABLE_THETA}" -eq '1' ]; then flag_theta='--enable-use-theta'; fi
if [ "${ENABLE_OPENMP}" -eq '1' ]; then flag_openmp='--enable-use-openmp'; fi

chmod +x configure
if [ -d lib/.deps ]; then make clean; fi

module load intel

# optimized configuration for Marconi (optimized compilation with Intel compiler on Intel Skylake processors)
./configure N_c=${NCOLORS} ST_dim=${STDIM} Num_levels=${NLEVELS} Num_threads=${NTHREADS} CC=icc CFLAGS='-O3 -axCORE-AVX512 -mtune=skylake -ip -ipo' LIBS="-ldl -lz -lc" ${flag_openmp} ${flag_theta}

# optimized configuration for Marconi (optimized compilation with Intel compiler on Intel Icelake processors)
#./configure N_c=${NCOLORS} ST_dim=${STDIM} Num_levels=${NLEVELS} Num_threads=${NTHREADS} CC=icc CFLAGS='-O3 -axCORE-AVX512 -mtune=icelake -ip -ipo' LIBS="-ldl -lz -lc" ${flag_openmp} ${flag_theta}

# compile
make ${compile_targets} -j 18
